### ISSUE TITLE
Segmentation fault when ACL is used

### ISSUE THREAD

**Issue by mike-2020** [OAID/Tengine#1354]
RK3399
Ubuntu 20.04
Latest Tengine source code, ACL v20.05
After successfully compile, run example below:
sudo ./tm_mobilenet_ssd_acl -m ~/models/Tengine/mobilenet_ssd/mobilenet_ssd.tmfile -i ../../pose.jpg -r 20 -t 1
会产生core文件，崩溃的栈信息如下。没有acl的命令行可以正常工作。

#0  0x0000000000000000 in ?? ()
#1  0x0000007fa6324358 in clSVMAlloc () from /home/xxxxx/Tengine/3rdparty/acl/lib/libarm_compute_core.so
#2  0x0000007fa6c81f08 in arm_compute::ICLSVMMemoryRegion::ICLSVMMemoryRegion(arm_compute::CLCoreRuntimeContext*, unsigned long, unsigned long, unsigned long) () from /home/xxxxx/Tengine/3rdparty/acl/lib/libarm_compute.so
#3  0x0000007fa6c821b4 in arm_compute::CLFineSVMMemoryRegion::CLFineSVMMemoryRegion(arm_compute::CLCoreRuntimeContext*, unsigned long, unsigned long, unsigned long) () from /home/xxxxx/Tengine/3rdparty/acl/lib/libarm_compute.so
#4  0x0000007fa6c88d5c in arm_compute::(anonymous namespace)::allocate_region(arm_compute::CLCoreRuntimeContext*, unsigned long, unsigned int) [clone .constprop.0] () from /home/xxxxx/Tengine/3rdparty/acl/lib/libarm_compute.so
#5  0x0000007fa6c894b4 in arm_compute::CLTensorAllocator::allocate() ()
   from /home/xxxxx/Tengine/3rdparty/acl/lib/libarm_compute.so
#6  0x0000007fa6cdbcec in arm_compute::CLGEMM::configure_reshaped_v1(arm_compute::CLCompileContext const&, arm_compute::ICLTensor const*, arm_compute::ICLTensor const*, arm_compute::ICLTensor const*, arm_compute::ICLTensor*, float, float, arm_compute::GEMMInfo const&) () from /home/xxxxx/Tengine/3rdparty/acl/lib/libarm_compute.so
#7  0x0000007fa6ce098c in arm_compute::CLGEMM::configure(arm_compute::CLCompileContext const&, arm_compute::ICLTensor const*, arm_compute::ICLTensor const*, arm_compute::ICLTensor const*, arm_compute::ICLTensor*, float, float, arm_compute::GEMMInfo const&) () from /home/xxxxx/Tengine/3rdparty/acl/lib/libarm_compute.so
#8  0x0000007fa6ce2d38 in arm_compute::CLGEMMConvolutionLayer::configure_mm(arm_compute::CLCompileContext const&, arm_compute::ICLTensor const*, arm_compute::ICLTensor const*, arm_compute::ICLTensor const*, arm_compute::ICLTensor*, arm_compute::GEMMLowpOutputStageInfo const&, int, arm_compute::ActivationLayerInfo const&) ()
   from /home/xxxxx/Tengine/3rdparty/acl/lib/libarm_compute.so
#9  0x0000007fa6ce5ca8 in arm_compute::CLGEMMConvolutionLayer::configure(arm_compute::CLCompileContext const&, arm_compute::ICLTensor const*, arm_compute::ICLTensor const*, arm_compute::ICLTensor const*, arm_compute::ICLTensor*, arm_compute::PadStrideInfo const&, arm_compute::WeightsInfo const&, arm_compute::Size2D const&, arm_compute::ActivationLayerInfo const&, unsigned int) () from /home/xxxxx/Tengine/3rdparty/acl/lib/libarm_compute.so
#10 0x0000007fa6ca8c4c in arm_compute::CLConvolutionLayer::configure(arm_compute::CLCompileContext const&, arm_compute::ICLTensor*, arm_compute::ICLTensor const*, arm_compute::ICLTensor const*, arm_compute::ICLTensor*, arm_compute::PadStrideInfo const&, arm_compute::WeightsInfo const&, arm_compute::Size2D const&, arm_compute::ActivationLayerInfo const&, bool, unsigned int) () from /home/xxxxx/Tengine/3rdparty/acl/lib/libarm_compute.so
#11 0x0000007fa6ca8e4c in arm_compute::CLConvolutionLayer::configure(arm_compute::ICLTensor*, arm_compute::ICLTensor const*, arm_compute::ICLTensor const*, arm_compute::ICLTensor*, arm_compute::PadStrideInfo const&, arm_compute::WeightsInfo const&, arm_compute::Size2D const&, arm_compute::ActivationLayerInfo const&, bool, unsigned int) ()
   from /home/xxxxx/Tengine/3rdparty/acl/lib/libarm_compute.so
--Type <RET> for more, q to quit, c to continue without paging--
#12 0x0000007fa71803fc in CLGraph::AddConvolutionLayer(node*) ()
   from /home/xxxxx/Tengine/build-acl-arm64/source/libtengine-lite.so
#13 0x0000007fa717c068 in CLGraph::CreateACLGraph(subgraph*, arm_compute::DataType, bool) ()
   from /home/xxxxx/Tengine/build-acl-arm64/source/libtengine-lite.so
#14 0x0000007fa717c470 in CLGraph::prerun(subgraph*, acl_option*) ()
   from /home/xxxxx/Tengine/build-acl-arm64/source/libtengine-lite.so
#15 0x0000007fa7196748 in sched_prerun () from /home/xxxxx/Tengine/build-acl-arm64/source/libtengine-lite.so
#16 0x0000007fa70c27d4 in prerun_graph_multithread ()
   from /home/xxxxx/Tengine/build-acl-arm64/source/libtengine-lite.so
#17 0x00000055555d19bc in main ()

**Comment by DongLZY** [comment]
tengine-lite library version: 1.5-dev
ACL initialized
Segmentation fault
这是什么原因？一开始还能运行，显示找不到opencl，现在就直接报错了？
