### ISSUE TITLE
Core dumped when trying to convert Tensorflow model (.pb) to .tmfile using convert_model_to_tm tool

### ISSUE THREAD

**Issue by kiner-shah** [OAID/Tengine#310]
I was trying to convert my tensorflow model (`.pb` file) to `.tmfile` using the `convert_model_to_tm tool` like this:

    ./convert_model_to_tm -f tensorflow -m my_model.pb -o my_model_tf.tmfile

It gave following error:
```
type is not same-----------------------
terminate called after throwing an instance of 'TEngine::bad_any_cast'
  what():  Bad any cast:  Expected: std::function<bool (TEngine::TFNode*, TEngine::TFGraph&, TEngine::StaticGraph*)>   Real: void
Aborted (core dumped)
```
I tried to see the stack trace using GDB, I got this:
```
(gdb) bt
#0  0x0000000000746e49 in raise (sig=6) at ../sysdeps/unix/sysv/linux/pt-raise.c:35
#1  0x00000000008a0dfa in abort ()
#2  0x000000000087b84d in __gnu_cxx::__verbose_terminate_handler() ()
#3  0x00000000007e9fa6 in __cxxabiv1::__terminate(void (*)()) ()
#4  0x00000000007e9ff1 in std::terminate() ()
#5  0x00000000007f4299 in __cxa_throw ()
#6  0x0000000000508330 in TEngine::TFSerializer::GenerateStaticGraph(TEngine::TFGraph&, TEngine::StaticGraph*) ()
#7  0x00000000005090a9 in TEngine::TFSerializer::LoadGraph(tensorflow::GraphDef&, TEngine::StaticGraph*) ()
#8  0x000000000050933d in TEngine::TFSerializer::LoadModel(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, TEngine::StaticGraph*) ()
#9  0x0000000000597b63 in real_vload_model(void*, char const*, char const*, void const*, int, __va_list_tag*) ()
#10 0x0000000000598a5b in vload_model(void*, char const*, char const*, void const*, int, __va_list_tag*) ()
#11 0x00000000005722d8 in create_graph ()
#12 0x0000000000400d45 in main ()
```

**Comment by QingChuanWS** [comment]
I have the same situation, Some people say it is because some ops are not supported
